; This file contains color constants
; All Colors are from 256 VGA standard Palette
; View the complete palette at https://upload.wikimedia.org/wikipedia/commons/6/66/VGA_palette_with_black_borders.svg


color_red EQU 28h
color_dark_red EQU 70h

color_blue EQU 09h

color_orange EQU 02Bh
color_light_orange EQU 5Bh

color_green EQU 02h
color_light_green EQU 60h
color_bright_green EQU 2fh

color_black EQU 00h
color_white EQU 0Fh


color_background EQU color_green