; This file contains color constants
; All Colors are from 256 VGA standard Palette
; View the complete palette at https://upload.wikimedia.org/wikipedia/commons/6/66/VGA_palette_with_black_borders.svg

COLOR_RED EQU 28h
COLOR_DARK_RED EQU 70h

COLOR_BLUE EQU 01h
COLOR_LIGHT_BLUE EQU 09h


COLOR_ORANGE EQU 2Bh
COLOR_LIGHT_ORANGE EQU 5Bh

COLOR_GREEN EQU 02h
COLOR_LIGHT_GREEN EQU 60h
COLOR_BRIGHT_GREEN EQU 2Fh

COLOR_BLACK EQU 00h
COLOR_WHITE EQU 0Fh


COLOR_BACKGROUND EQU COLOR_GREEN